Page({
    data:{
        chatList:[
            {
                id:'1',
                imgUrl:'../../resources/man1.jpeg',
                name:'吴彦祖',
                content:'帅不过我',
                time:'17:53'
            },
            {
                id:'2',
                imgUrl:'../../resources/man2.jpg',
                name:'张震',
                content:'我是功夫之王',
                time:'15:43'
            },
            {
                id:'3',
                imgUrl:'../../resources/woman1.jpg',
                name:'张曼玉',
                content:'你好，在吗',
                time:'20:53'
            }
        ]
    }
})